services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: MoviesCluster

volumes:
  cassandra_data: